version: '3.8'

services:
  # Наш сервер
  app:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=sweets_db

  # База данных
  db:
    image: mysql:8.0
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # Добавь это
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sweets_db
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql